- name: Demo on loops
  hosts: localhost
  tasks:
    - name: Loop Example
      debug:
        msg: Fruit = {{item}}
      loop:
        - apple
        - banana
    - name: Loop Example with map
      debug:
        msg: Fruit name = {{item.name}}, Quantity = {{item.quantity}}
      loop:
        - {name: apple, quantity: 59}
        - {name: banana, quantity: 69}